name: "Stream mqtt from Enphase Envoy"
description: "Converts Envoy Json to mqtt"
version: "1.0.9.5"
slug: "envoy_to_mqtt_json"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  MQTT_HOST: ip.address.of.homeasistant
  MQTT_USER: mqtt.user
  MQTT_PASSWORD: mqtt.password
  MQTT_PORT: 1883
  ENVOY_HOST: envoy.local
  ENVOY_PASSWORD: secret
  TOPIC_FREEDS: Inverter/GridWatts
  ENVOY_TOKEN: generate token in https://entrez.enphaseenergy.com/entrez_tokens
schema:
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_PORT: int
  ENVOY_HOST: str
  ENVOY_PASSWORD: str  
  TOPIC_FREEDS: str
  ENVOY_TOKEN: str
