services:
  enphase-envoy-mqtt:
    container_name: enphase-envoy-mqtt
    image: ghcr.io/bastyjuice/enphase-envoy-mqtt:latest
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ./options.json:/data/options.json:rw
      - ./token.txt:/data/token.txt:rw      
    environment:
      - TZ=Europe/Berlin
